export const INITIALIZE_CONTAINER = 'INITIALIZE_CONTAINER';
export const DESTROY_CONTAINER = 'DESTROY_CONTAINER';
export const UPDATE_VALUE = 'UPDATE_VALUE';
export const CHANGE_TAB = 'CHANGE_TAB';
export const CREATE_BATCH = 'CREATE_BATCH';
