export const ADD_REPEATER_ROW = 'ADD_REPEATER_ROW';
export const DELETE_REPEATER_ROW = 'DELETE_REPEATER_ROW';
export const ADD_NEW_REPEATER_ROW = 'ADD_NEW_REPEATER_ROW';
export const INSERT_CLONED_REPEATER_ROW = 'CLONE_REPEATER_ROW';
export const CLONE_REPEATER_ROW = 'CLONE_REPEATER_ROW';
