import React from 'react';
import Field from './../Field.jsx';
import Tab from './../Tab.jsx';
import Group from './../Field/Repeater/Group.jsx';
import ConditionalLogic from './../ConditionalLogic.jsx';

/**
 * Handles the generation of fields as react elements based on simple arrays, generated by PHP.
 */
export default class Loader {
	/**
	 * Creates a new instance of the class based on given fields.
	 *
	 * @param {Array.Object} source An array with field descriptors.
	 */
	constructor( source ) {
		this.source = source;
	}

	/**
	 * Loads the React equivalents of standard fields.
	 *
	 * @return {Array.React.Element}
	 */
	load() {
		this.fields = [];
		this.generateFields( this.source );
		return this.fields;
	}

	generateFields( source ) {
		source.forEach( field => {
			this.fields.push( this.parseField( field ) );
		});
	}

	wrapFieldInConditionalLogic( children, field ) {
		if( ! field.dependencies || ! field.dependencies.length ) {
			return children;
		}

		const { Group, Rule } = ConditionalLogic;

		return <ConditionalLogic key={ field.name }>
			{ children }

			{ field.dependencies.map( ( group, index ) => <Group key={ index }>
				{ group.map( ( rule, index, ) =>
					<Rule { ...rule } key={ index } />
				) }
			</Group> ) }
		</ConditionalLogic>
	}

	parseField( field ) {
		if( 'Tab' === field.type ) {
			return this.wrapFieldInConditionalLogic(
				React.createElement( Tab, Object.assign( {}, field, {
					children: ( new Loader( field.children ).load() ),
					key:      field.name
				})),
				field
			)
		}

		// Prepare the field
		if( 'Repeater' === field.type ) {
			field.children = field.groups.map( group => {
				return React.createElement( Group, {
					...group,
					key: group.type,
					children: ( new Loader( group.fields ) ).load()
				});
			});
		} else if( 'Complex' === field.type ) {
			field.group.children = ( new Loader( field.group.fields ) ).load();
		}

		return this.wrapFieldInConditionalLogic(
			<Field { ...field } key={ field.name } />,
			field
		);
	}
}
